app/urls.py
from django.urls import path

from .views import (
    UserListView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    GroupListView,
    GroupCreateView,
    GroupUpdateView,
    GroupDeleteView,
)

urlpatterns = [
    path("users/", UserListView.as_view(), name="user-list"),
    path("users/create/", UserCreateView.as_view(), name="user-create"),
    path(
        "users/<int:pk>/update/", UserUpdateView.as_view(), name="user-update"
    ),
    path(
        "users/<int:pk>/delete", UserDeleteView.as_view(), name="user-delete"
    ),
    path("groups/", GroupListView.as_view(), name="group-list"),
    path("groups/create/", GroupCreateView.as_view(), name="group-create"),
    path(
        "groups/<int:pk>/update/",
        GroupUpdateView.as_view(),
        name="group-update",
    ),
    path(
        "groups/<int:pk>/delete/",
        GroupDeleteView.as_view(),
        name="group-delete",
    ),
]

app_name = "app"

vnv_test_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.contrib.auth.models import Group
from django.db import models


class CustomGroup(Group):
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = "Custom Group"
        verbose_name_plural = "Custom Groups"


class CustomUser(models.Model):
    username = models.CharField(max_length=30, unique=True)
    group = models.ForeignKey(
        CustomGroup,
        blank=True,
        related_name="users",
        null=True,
        on_delete=models.PROTECT,
    )
    created = models.DateTimeField(auto_now_add=True)

app/views.py
from django.urls import reverse_lazy
from django.views import generic

from .models import CustomGroup, CustomUser


class UserListView(generic.ListView):
    model = CustomUser


class UserCreateView(generic.CreateView):
    model = CustomUser
    fields = "__all__"
    success_url = reverse_lazy("app:user-list")


class UserUpdateView(generic.UpdateView):
    model = CustomUser
    fields = "__all__"
    success_url = reverse_lazy("app:user-list")


class UserDeleteView(generic.DeleteView):
    model = CustomUser
    success_url = reverse_lazy("app:user-list")


class GroupListView(generic.ListView):
    model = CustomGroup


class GroupCreateView(generic.CreateView):
    model = CustomGroup
    success_url = reverse_lazy("app:group-list")
    fields = (
        "name",
        "description",
    )


class GroupUpdateView(generic.UpdateView):
    model = CustomGroup
    success_url = reverse_lazy("app:group-list")
    fields = (
        "name",
        "description",
    )


class GroupDeleteView(generic.DeleteView):
    model = CustomGroup
    success_url = reverse_lazy("app:group-list")

templates/app/customgroup_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <br><br>
  <h1 class="ms-5">Delete Group?</h1>
  <br>
  <form class="ms-5" action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  {% include "includes/go_back_button.html" %}
  </form>
{% endblock %}

templates/app/customgroup_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <br>
  <h1>{{ object|yesno:"Update,Create" }} Group</h1>
  <hr>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  {% include "includes/go_back_button.html" %}
  </form>
{% endblock %}

templates/app/customgroup_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Group List
    <a href="{% url 'app:group-create' %}"
       class="btn btn-primary link-to-page ms-5 mt-5">
      Add Group
    </a>
  </h1>
  <hr>
  {% if customgroup_list %}
    <table class="table w-75">
      <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Desctiption</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      {% for group in customgroup_list %}
        <tr>
          <th scope="row">{{ group.id }}</th>
          <td>{{ group.name }}</td>
          <td>{{ group.description }}</td>
          <td>
            <a href="{% url 'app:group-update' group.id %}" class="btn btn-outline-gray btn-sm">Edit</a>
            {% if not group.users.exists %}
            <a href="{% url 'app:group-delete' group.id %}" class="btn btn-outline-danger btn-sm ms-2">Delete</a>
            {% endif %}
          </td>
      </tbody>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no groups</p>
  {% endif %}
{% endblock %}

templates/app/customuser_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <br><br>
  <h1 class="ms-5">Delete User?</h1>
  <br>
  <form class="ms-5" action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  {% include "includes/go_back_button.html" %}
  </form>
{% endblock %}

templates/app/customuser_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <br>
  <h1>{{ object|yesno:"Update,Create" }} User</h1>
  <hr>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  {% include "includes/go_back_button.html" %}
  </form>
{% endblock %}

templates/app/customuser_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    User List
    <a href="{% url 'app:user-create' %}"
       class="btn btn-primary link-to-page ms-5 mt-5">
      Add User
    </a>
  </h1>
  <hr>
  {% if customuser_list %}
    <table class="table">
      <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Username</th>
        <th scope="col">Created</th>
        <th scope="col">Group</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      {% for user in customuser_list %}
        <tr>
          <th scope="row">{{ user.id }}</th>
          <td>{{ user.username }}</td>
          <td>{{ user.created }}</td>
          <td>{{ user.group }}</td>
          <td>
            <a href="{% url 'app:user-update' user.id %}" class="btn btn-outline-gray">Edit</a>
            <a href="{% url 'app:user-delete' user.id %}" class="btn btn-outline-danger">Delete</a>
          </td>
      </tbody>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no users</p>
  {% endif %}
{% endblock %}

templates/app/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <br>
  <h1>{{ object|yesno:"Update,Create" }} User</h1>
  <hr>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/app/user_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    User List
    <a href="{% url 'app:user-create' %}"
       class="btn btn-primary link-to-page ms-5 mt-5">
      Add User
    </a>
  </h1>
  <hr>
  {% if user_list %}
    <table class="table">
      <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Email</th>
        <th scope="col">Group</th>
        <th scope="col">Admin</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      {% for user in user_list %}
        <tr>
          <th scope="row">{{ user.id }}</th>
          <td>{{ user.email }}</td>
          <td>{{ user.group }}</td>
          <td>
            {% if user.is_staff %}
              <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked disabled/>
            {% else %}
              <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" disabled/>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'app:user-update' user.id %}" class="btn btn-outline-gray">Edit</a>
            <a href="" class="btn btn-outline-danger">Delete</a>
          </td>
      </tbody>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no users</p>
  {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.css"
  rel="stylesheet"
/>
  <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"
></script>
</body>

</html>

templates/includes/go_back_button.html
<a href="javascript:history.go(-1)" class="btn btn-dark">Go back</a>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item mt-5"><a href="{% url 'app:user-list' %}">Users</a></li>
  <li class="list-group-item"><a href="{% url 'app:group-list' %}">Groups</a></li>
</ul>